from openerp import models, fields, api, _


class HrPayslip(models.Model):
    _inherit = 'product.template'

    manufacturer = fields.Char('Manufacturer')
    manufacturing_date = fields.Date('Manufacturing Date')
    place_origin = fields.Char('Place of Origin')
    style_no = fields.Char('Style No')
    series_no = fields.Char('Series No')

    destination_location = fields.Many2one(
        'stock.location', "Destination Location",
        company_dependent=True, domain=[('usage', 'like', 'internal')],
        help="This stock location will be used, instead of the default one, as the source location for stock moves generated by manufacturing orders.")

class StockPicking(models.Model):
    _inherit = 'stock.picking'

    create_date = fields.Datetime("Creation Date", readonly=True, index=True)
    write_date = fields.Datetime("Update Date", readonly=True)
    write_uid = fields.Many2one('res.users', "Updated by Name", readonly=True )