
{
    'name' : 'Yuko Inventory',
    'version' : '1.0',
    'author' : 'Odoo Bangladesh',
    'summary': 'Inventory',
    'description': """
    
    """,
    'category': '',
    'sequence': 4,
    'website' : '',
    'depends' : ['product',
                 'purchase',
                 'sale',
                 'stock',
                 'mail',
                 'stock_picking_extend',
                 'indent_type',
                 'stock_indent',
                 'procurement',
                 "product_gate_in",
                 'stock_gate_in',
                 'stock_gate_out',
                 'stock_picking_mrr',
                 'gbs_stock_product',
                 'stock_custom_summary_report',
                 'yuko_report_layout',],
    'data' : ["security/security.xml",
              'security/ir.model.access.csv',
              'views/product_template_views.xml',
              'views/indent_indent_views.xml',
              #'views/product_get_in_view.xml',
              'views/stock_gate_in_view.xml',
              'views/stock_move_view.xml',
              'views/stock_gate_out_view.xml',
              'reports/inherit_stock_indent_report.xml',
              "reports/gate_pass_report_view.xml",
              'reports/inherit_stockpricking_operations.xml',
              "reports/inherit_template_mrr.xml",
              'reports/inherit_stock_inventory_report_view.xml'],
    'auto_install': False,
    'application': False,
    'installable': True,
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
